name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '2.7'
          os: ubuntu-20.04
        - python: '3.3'
          os: ubuntu-18.04
        - python: '3.4'
          os: ubuntu-18.04
        - python: '3.5'
          os: ubuntu-18.04
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-20.04
        - python: '3.11-dev'
          os: ubuntu-20.04
          broken: broken
        - python: '3.10'
          os: windows-2019
    runs-on: ${{matrix.os}}
    continue-on-error: ${{(matrix.broken && true) || false}}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: run tests
      run: |
        PYTHONPATH=$PWD python test/test.py --verbose
    - name: check whether setup.py works in the C locale
      run: |
        LC_ALL=C python setup.py --version
    - name: install via setup.py
      run: |
        python setup.py install
    - name: check import
      run: |
        cd /
        python -c 'import slownie'
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra .
    - name: run pyflakes
      run: |
        pyflakes=pyflakes
        if [[ ${{matrix.python}} = 3.3 ]]; then pyflakes+='<2'; fi
        python -m pip install $pyflakes
        python -m pyflakes .
    - name: run pylint
      run: |
        python -m pip install pylint
        # work-around for <https://github.com/GrahamDumpleton/wrapt/issues/196>:
        sed -i -e 's/, formatargspec$//' ${{env.pythonLocation}}/lib/python*/site-packages/wrapt/decorators.py
        python -m pylint *.py */*.py
      if:
        matrix.python != '3.3' &&
        matrix.python != '3.4' &&
        ! startsWith(matrix.os, 'windows-')
    - name: check docs
      run: |
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
        python -m pip install docutils pygments
        private/check-rst
      if: true && ! startsWith(matrix.os, 'windows-')

# vim:ts=2 sts=2 sw=2 et
